version: '3'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    #    volumes:
    #      - 'zookeeper_data:/bitnami/zookeeper'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
      - '29092:29092'
    #    volumes:
    #      - 'kafka_data:/bitnami/kafka'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=INTERNAL_LISTENER://kafka:9092,EXTERNAL_LISTENER://kafka:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL_LISTENER://kafka:9092,EXTERNAL_LISTENER://localhost:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL_LISTENER:PLAINTEXT,EXTERNAL_LISTENER:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL_LISTENER
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_LOG_DIR=/bitnami/kafka/tmp/kafka-logs-1
    depends_on:
      - zookeeper
