version: '3'

services:
  service:
    image: winelab-parser-service:latest
    ports:
      - 8080:8080
    environment:
      - S_KAFKA_BOOTSTRAP_HOST=kafka:9092
    depends_on:
      - kafka
      - mongodb